endpoints:
  main: /api
  prices: /prices

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    format:
      date-time: yyyy-MM-dd HH.mm.ss
    